apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
