apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pods
  name: pods
spec:
  containers:
  - args:
    - po
    image: nginx
    name: pods
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
